### PR TITLE
Add initial Draw.IO flowchart

### LINKED ISSUE #27: Create an Airseeker V2 flowchart
There are supposed to be three loops:
1. Periodically fetches the signed API URLs
2. Periodically fetches signed data from the signed APIs
3. Periodically updates on-chain values in batches in a staggered way

### PR DESCRIPTION
**Pull request by aquarat**
This adds the Draw.IO diagram to this repository. Accessible via https://draw.io

Authorise GH -> Select repo -> Select branch -> Select file
(27-add-flowchart -> airseeker_v2_pipeline.drawio)

Closes #27

### CODE REVIEW

**Comment by Siegrift** [comment]
This should be documented in README how to access it.

Also can we make:
```
Authorise GH -> Select repo -> Select branch -> Select file
(27-add-flowchart -> airseeker_v2_pipeline.drawio)
```

somehow encoded in the URL ? Such that when you click a link you will get the file displayed immediatelly?

**Comment by Siegrift** [comment]
Actually now that I think about it... If I edit this diagram using the [diagrams URL](https://app.diagrams.net/#G1pIP1M1n_BW5-FD8_VTAWhX1vhuR2Moho) the content in the repo will not be updated.

It makes it pretty annoying to always make a PR whenever we change the diagram. I'd just put the URL in README and be done with it.

**Comment by BTT21000** [comment]
An alternative solution is to use [Mermaid](https://mermaid.live/) and embed the diagram URL in the README.md

**Comment by aquarat** [comment]
> Mermaid

Mermaid looks very cool 🚀

**Comment by aquarat** [comment]
Diagrams/Draw.IO has a URL export function and various other tools that could probably be used to automate things, and can be used for embedding too... but ultimately imo we can't spend too much time on this 🤷

**Comment by aquarat** [comment]
LGTM 🤷 I can't reveiw because I created the PR :D

**Comment by bbenligiray** [comment]
> Authorise GH 

Yikes, I'd recommend having it read from https://raw.githubusercontent.com/api3dao/airseeker-v2/b57506ffeafb45dcc79bbce083798de0f759323d/airseeker_v2_pipeline.drawio instead

**Comment by bbenligiray** [comment]
This looks out of date. What do we do about it?

**Comment by Siegrift** [comment]
I'd just put the link to README, [the link](https://drive.google.com/file/d/1pIP1M1n_BW5-FD8_VTAWhX1vhuR2Moho/view) always shows the up to date content.

**Review by vponline — APPROVED** [review]
LGTM 😄

**Pull request merged**
